
SELECT B.AUTHOR_ID, 
    A.AUTHOR_NAME, 
    B.CATEGORY, 
   SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK B
JOIN BOOK_SALES S 
    ON (S.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31')
    AND S.BOOK_ID = B.BOOK_ID
JOIN AUTHOR A  
    ON A.AUTHOR_ID = B.AUTHOR_ID
GROUP BY 
    B.CATEGORY, 
    B.AUTHOR_ID
ORDER BY 
    B.AUTHOR_ID ASC, 
    B.CATEGORY DESC