SELECT D4.ID
FROM ECOLI_DATA D4
JOIN (SELECT D1.ID
    FROM ECOLI_DATA D1
    JOIN (
        SELECT ID
        FROM ECOLI_DATA
        WHERE PARENT_ID IS NULL) D2 ON D2.ID = D1.PARENT_ID
    ) AS D3 ON D4.PARENT_ID = D3.ID

    
