SELECT ANIMAL_ID, NAME
FROM    (SELECT I.ANIMAL_ID ,RANK() OVER(ORDER BY O.DATETIME-I.DATETIME DESC) AS R, O.NAME
    FROM ANIMAL_INS I
    JOIN ANIMAL_OUTS O ON O.ANIMAL_ID = I.ANIMAL_ID) AS T
WHERE R<3
ORDER BY R ASC 