SELECT CAR_ID, CAR_TYPE, FEE
FROM
    (SELECT C.CAR_ID,C.CAR_TYPE, ROUND(C.DAILY_FEE*30*(100-D.DISCOUNT_RATE)/100,0) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN  D ON D.DURATION_TYPE = '30일 이상' AND D.CAR_TYPE = C.CAR_TYPE 
    WHERE NOT EXISTS
        (SELECT *
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        WHERE (H.END_DATE >= '2022-11-01')
                AND (H.START_DATE <= '2022-11-30' )
            AND H.CAR_ID = C.CAR_ID
        ) AND (C.CAR_TYPE = 'SUV' OR C.CAR_TYPE = '세단')) AS T
WHERE FEE >=500000 AND FEE <=2000000

