WITH JUL AS (
    SELECT SHIPMENT_ID, SUM(TOTAL_ORDER) AS SUM_ORDER, FLAVOR
    FROM JULY
    GROUP BY FLAVOR
),
FIR AS (
    SELECT SHIPMENT_ID, SUM(TOTAL_ORDER) AS SUM_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR
)
SELECT FLAVOR
FROM FIR AS F
JOIN JUL AS J ON J.SHIPMENT_ID = F.SHIPMENT_ID
ORDER BY F.SUM_ORDER+J.SUM_ORDER DESC
LIMIT 3