WITH RECURSIVE date AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 
    FROM date
    WHERE HOUR<23),
outs AS(
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS c
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
)
    
SELECT D.HOUR, IFNULL(o.c,0)
FROM date as D
LEFT JOIN outs AS o ON o.HOUR = D.HOUR


