WITH FRONT_MASK AS(
SELECT SUM(CASE WHEN CATEGORY = 'Front End' THEN CODE ELSE 0 END) AS FRONT
FROM SKILLCODES )

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM(
    SELECT 
        CASE
            WHEN D.SKILL_CODE & M.FRONT >0 THEN 'Front'
        END AS CATEGORY,
    D.ID,
    D.EMAIL,
    D.FIRST_NAME,
    D.LAST_NAME
    FROM DEVELOPERS D
    CROSS JOIN FRONT_MASK M
) AS T
WHERE T.CATEGORY IS NOT NULL
ORDER BY ID ASC 