SELECT USER_ID, NICKNAME, B.TOTAL_SALES 
FROM USED_GOODS_USER U
JOIN (
    SELECT SUM(PRICE) AS TOTAL_SALES, WRITER_ID
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000) B ON B.WRITER_ID = U.USER_ID
ORDER BY B.TOTAL_SALES ASC
