SELECT E.EMP_NO, 
E.EMP_NAME, 
G.R AS GRADE,
CASE 
    WHEN G.R = 'S' THEN E.SAL*0.2
    WHEN G.R = 'A' THEN E.SAL*0.15
    WHEN G.R = 'B' THEN E.SAL*0.1
    ELSE 0
END AS BONUS
FROM HR_EMPLOYEES E
JOIN (SELECT EMP_NO,CASE 
        WHEN AVG(SCORE) >=96 THEN 'S'
        WHEN AVG(SCORE) >=90 THEN 'A'
        WHEN AVG(SCORE) >=80 THEN 'B'
        ELSE 'C'
        END AS R
    FROM HR_GRADE 
    GROUP BY EMP_NO) G ON E.EMP_NO = G.EMP_NO
ORDER BY E.EMP_NO ASC
