SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
JOIN (SELECT SUM(CODE) AS SUMCODE
     FROM SKILLCODES
     WHERE NAME = 'Python' or NAME = 'C#') S ON D.SKILL_CODE & S.SUMCODE > 0
ORDER BY D.ID

