SELECT ID,
        FISH_NAME,
        LENGTH
FROM (
    SELECT I.ID AS ID,
            N.FISH_NAME AS FISH_NAME,
            I.LENGTH AS LENGTH,
            RANK() OVER(PARTITION BY I.FISH_TYPE ORDER BY I.LENGTH DESC) AS R
    FROM FISH_INFO I
    JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
    ) as T
WHERE R=1
ORDER BY ID
