SELECT G.SUMSCORE AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E
JOIN 
    (SELECT EMP_NO,SUM(SCORE) AS SUMSCORE, RANK() OVER(ORDER BY SUM(SCORE) DESC) AS R
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO) G ON E.EMP_NO = G.EMP_NO
WHERE G.R=1
    
     
