WITH FRONT AS(
    SELECT SUM(CODE) AS SUMCODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'),
CSHARP AS(
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'C#'),
PYTHON AS(
    SELECT CODE 
    FROM SKILLCODES
    WHERE NAME = 'Python')
    
SELECT GRADE,ID,EMAIL
FROM    (SELECT CASE 
        WHEN SKILL_CODE & F.SUMCODE >= 1 AND SKILL_CODE & P.CODE THEN 'A'
        WHEN SKILL_CODE & C.CODE = C.CODE THEN 'B'
        WHEN SKILL_CODE & F.SUMCODE >=1 THEN 'C'
        END AS GRADE,
        ID,
        EMAIL
    FROM DEVELOPERS
    CROSS JOIN FRONT F
    CROSS JOIN CSHARP C
    CROSS JOIN PYTHON P
    ) AS T
WHERE GRADE IS NOT NULL
ORDER BY GRADE ASC, ID ASC